<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>StrictDoc Syntax: version 1.0</string>
	<key>fileTypes</key>
	<array>
		<string>sdoc</string>
	</array>
	<key>firstLineMatch</key>
	<string>^\[DOCUMENT\]$</string>
	<key>name</key>
	<string>StrictDoc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#document</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#grammar</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#section</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#requirement</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#freetext</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>choice_boolean</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(True|False)\b</string>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</array>
		</dict>
		<key>choice_enable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(On|Off)\b</string>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</array>
		</dict>
		<key>document</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\.)^\[DOCUMENT\]$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^$</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#document_field_name</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#document_options</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>document_field_name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\b(TITLE|UID|VERSION|CLASSIFICATION)\b:</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>document_options</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^OPTIONS:$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^$</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#document_options_markup</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#document_options_auto_levels</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#document_options_requirement_style</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#document_options_requirement_in_toc</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>document_options_auto_levels</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^\s\sAUTO_LEVELS:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>constant.numeric</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#choice_enable</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>document_options_markup</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.character</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(^\s\sMARKUP:)\s\b(RST|Text|HTML)\b$</string>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</array>
		</dict>
		<key>document_options_requirement_in_toc</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^\s\sREQUIREMENT_IN_TOC:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>constant.numeric</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#choice_boolean</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>document_options_requirement_style</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.character</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(^\s\sREQUIREMENT_STYLE:)\s\b(Inline|Simple|Table|Zebra|Narrative)\b$</string>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</array>
		</dict>
		<key>freetext</key>
		<dict>
			<key>begin</key>
			<string>^\[FREETEXT\]$</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.rst</string>
			<key>end</key>
			<string>^\[\/FREETEXT\]$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rst</string>
				</dict>
			</array>
		</dict>
		<key>grammar</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\[\b(GRAMMAR)\b\]$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^$</string>
					<key>name</key>
					<string>emphasis</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>^ELEMENTS:</string>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<dict>
							<key>match</key>
							<string>^(-|\s)\s(TAG|FIELDS):</string>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#grammar_field_title</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#grammar_field_type</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#grammar_field_required</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>grammar_field_reference_choice</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(ParentReqReference|FileReference|BibReference)\b</string>
					<key>name</key>
					<string>constant.character</string>
				</dict>
			</array>
		</dict>
		<key>grammar_field_required</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^\s\s\s\sREQUIRED:)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#choice_boolean</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>grammar_field_title</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^\s\s-\sTITLE:)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b(UID|REFS|TITLE|STATEMENT|RATIONALE|COMMENT)\b</string>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>grammar_field_type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^\s\s\s\sTYPE:)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b(String|Tag|SingleChoice\(|MultipleChoice\(|Reference\()\b</string>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#grammar_field_reference_choice</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\[\/(REQUIREMENT|GRAMMAR|DOCUMENT)\]</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\[\/?SECTION\]$</string>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</array>
		</dict>
		<key>requirement</key>
		<dict>
			<key>begin</key>
			<string>^\[REQUIREMENT\]$</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rst_field_value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#requirement_fields</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#requirement_field_params</string>
				</dict>
			</array>
		</dict>
		<key>requirement_field_params</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^(-\sTYPE|\s\sVALUE):\s</string>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</array>
		</dict>
		<key>requirement_fields</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^(UID|REFS|TITLE|STATEMENT|RATIONALE|COMMENT):\s</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>rst</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.restructuredtext</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>comment</key>
			<string>custom bundle name for reStructuredText: text.restructuredtext. </string>
			<key>match</key>
			<string>(.*)</string>
		</dict>
		<key>rst_field_value</key>
		<dict>
			<key>begin</key>
			<string>&gt;&gt;&gt;$</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.rst</string>
			<key>end</key>
			<string>^&lt;&lt;&lt;$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rst</string>
				</dict>
			</array>
		</dict>
		<key>section</key>
		<dict>
			<key>begin</key>
			<string>^\[SECTION\]$</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^(UID|TITLE):\s</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.sdoc</string>
	<key>uuid</key>
	<string>13E807FD-8F26-455A-9A3E-58C8B108CE64</string>
</dict>
</plist>
